### ISSUE TITLE
"vagrant up" not working

### ISSUE THREAD

**Issue by jagtalon** [shedd/duckpan-vagrant#15]
I'm getting this error when I first ran `vagrant up`. Not quite sure what the problem is. I'm using OS X 10.9.1

![screen shot 2014-02-09 at 3 36 56 pm](https://f.cloud.github.com/assets/81969/2121017/84a3cbac-91cf-11e3-9237-fc4d540fbf9b.png)

**Comment by shedd** [comment]
@jagtalon do you know if you're still having this issue?  Some improvements have been made recently to the dependencies, which might fix the issue.  Going to close this for now...
