### ISSUE TITLE
ridley's version locked at 1.5.3

### ISSUE THREAD

**Issue by zsan** [shedd/duckpan-vagrant#30]
Hi,

I ran bundle install and then i found:

`The bundle currently has ridley locked at 1.5.3.`

I opened `Gemfile` and i saw

`gem 'ridley', '~> 1.7.1'`

I think you need to update your Gemfile.lock to the repository.

**Comment by shedd** [comment]
fix pending merge: https://github.com/shedd/duckpan-vagrant/pull/32

**Comment by mikedep333** [comment]
Fixed. #32 was merged.
